/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForStudentsRouteImport } from './routes/for-students'
import { Route as ForEmployersRouteImport } from './routes/for-employers'
import { Route as ForCollegesRouteImport } from './routes/for-colleges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardEmployerRouteImport } from './routes/dashboard.employer'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForStudentsRoute = ForStudentsRouteImport.update({
  id: '/for-students',
  path: '/for-students',
  getParentRoute: () => rootRouteImport,
} as any)
const ForEmployersRoute = ForEmployersRouteImport.update({
  id: '/for-employers',
  path: '/for-employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCollegesRoute = ForCollegesRouteImport.update({
  id: '/for-colleges',
  path: '/for-colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmployerRoute = DashboardEmployerRouteImport.update({
  id: '/dashboard/employer',
  path: '/dashboard/employer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/for-colleges': typeof ForCollegesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-students': typeof ForStudentsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/for-colleges': typeof ForCollegesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-students': typeof ForStudentsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/for-colleges': typeof ForCollegesRoute
  '/for-employers': typeof ForEmployersRoute
  '/for-students': typeof ForStudentsRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/dashboard/employer': typeof DashboardEmployerRoute
  '/dashboard/student': typeof DashboardStudentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/for-colleges'
    | '/for-employers'
    | '/for-students'
    | '/marketplace'
    | '/pricing'
    | '/dashboard/employer'
    | '/dashboard/student'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/for-colleges'
    | '/for-employers'
    | '/for-students'
    | '/marketplace'
    | '/pricing'
    | '/dashboard/employer'
    | '/dashboard/student'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/for-colleges'
    | '/for-employers'
    | '/for-students'
    | '/marketplace'
    | '/pricing'
    | '/dashboard/employer'
    | '/dashboard/student'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  ForCollegesRoute: typeof ForCollegesRoute
  ForEmployersRoute: typeof ForEmployersRoute
  ForStudentsRoute: typeof ForStudentsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  DashboardEmployerRoute: typeof DashboardEmployerRoute
  DashboardStudentRoute: typeof DashboardStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-students': {
      id: '/for-students'
      path: '/for-students'
      fullPath: '/for-students'
      preLoaderRoute: typeof ForStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-employers': {
      id: '/for-employers'
      path: '/for-employers'
      fullPath: '/for-employers'
      preLoaderRoute: typeof ForEmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-colleges': {
      id: '/for-colleges'
      path: '/for-colleges'
      fullPath: '/for-colleges'
      preLoaderRoute: typeof ForCollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/employer': {
      id: '/dashboard/employer'
      path: '/dashboard/employer'
      fullPath: '/dashboard/employer'
      preLoaderRoute: typeof DashboardEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  ForCollegesRoute: ForCollegesRoute,
  ForEmployersRoute: ForEmployersRoute,
  ForStudentsRoute: ForStudentsRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  DashboardEmployerRoute: DashboardEmployerRoute,
  DashboardStudentRoute: DashboardStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
